spring.application.name=service

spring.datasource.url=jdbc:postgresql://localhost:55433/passwordman
spring.datasource.username=passwordman
spring.datasource.password=passwordman
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

passwordman.jwt-secret=hbfgvi348h3b39bfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
passwordman.jwt-access-expiration-millis=900000
passwordman.jwt-refresh-expiration-millis=604800000
passwordman.login-rate-limit-max-attempts=5
passwordman.login-rate-limit-block-duration-millis=300000
passwordman.refresh-rate-limit-max-attempts=5
passwordman.refresh-rate-limit-block-duration-millis=300000
passwordman.vault-unlock-rate-limit-max-attempts=5
passwordman.vault-unlock-rate-limit-block-duration-millis=300000
passwordman.bcrypt-strength=12

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

passwordman.encryption-key-ref=local-dev-key
passwordman.encryption-master-key-base64=MzEyMzEyMzEyMzEyMzEyMzEyMzEyMzEyMzEyMzEyMzE=

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:localhost+2.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=1